### ISSUE TITLE
A few issues need fixing for upcoming Home Assistant version 2022.2

### ISSUE THREAD

**Issue by vk2him** [pilotak/homeassistant-clientraw#13]
Hi,
I'm seeing the following errors in my logs warning that a methods will soon be deprecated in version 2022.2. Thanks

`Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for clientraw using this method at custom_components/clientraw/sensor.py, line 172: with async_timeout.timeout(10, loop=self.hass.loop):`

Each returned value in Clientraw displays this warning:

`022-01-08 08:49:47 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_temperature (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-08 08:49:47 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_indoor_temperature (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-08 08:49:47 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_humidity (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-08 08:49:47 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_indoor_humidity (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-08 08:49:47 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_wind_gust_last_hour (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-08 08:49:47 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_dewpoint (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by pilotak** [comment]
i will look into it

**Comment by ktn7419** [comment]
Hello pilotak: I just want to add that I am using this and I get the same warnings. However, I'm on HS version 2022.2.3 Thank you.

**Comment by vk2him** [comment]
I’m also on 2022.2.3. The error message now says it will be deprecated from 2022.3

**Comment by viamarit** [comment]
Yes, I'm using the 2022.3.0b3 and the integration does not start anymore for this error

**Comment by pilotak** [comment]
could you please try eb2e6fb393ee571d6eae482334f08c964e73f69b

**Comment by vk2him** [comment]
That seems to have resolved the issue - many thanks!!

**Comment by pilotak** [comment]
@viamarit could you please test it with 2022.03 version?

**Comment by ktn7419** [comment]
Hello Pavel,

I have also tried and it is now working.   Thank you

Gary

Wednesday, March 2, 2022, 4:38:37 PM, you wrote:


@viamarit could you please test it with 2022.03 version?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you commented.Message ID: ***@***.***>



-- 
Best regards,
 Gary                            ***@***.***

**Comment by vk2him** [comment]
> Hello Pavel, I have also tried and it is now working. Thank you Gary

Gary, are you using 2022.03?

**Comment by viamarit** [comment]
> @viamarit could you please test it with 2022.03 version?

I upgraded to 2022.03. Still does tot work. The error logged is:
2022-03-02 22:06:35 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_temperature (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
for each Entity

**Comment by ktn7419** [comment]
Hello vk2him,

Yes, just upgraded to 2022.03 today

Wednesday, March 2, 2022, 4:59:35 PM, you wrote:



Hello Pavel, I have also tried and it is now working. Thank you Gary
Gary, are you using 2022.03?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you commented.Message ID: ***@***.***>



-- 
Best regards,
 Gary                            ***@***.***

**Comment by viamarit** [comment]
The error in my actual 2022.03 - clientraw 2.1.1 is still:
2022-03-02 22:06:35 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up clientraw platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/clientraw/sensor.py", line 107, in async_setup_platform
await weather.async_update()
File "/config/custom_components/clientraw/sensor.py", line 187, in async_update
with async_timeout.timeout(10, loop=self.hass.loop):
TypeError: timeout() got an unexpected keyword argument 'loop'

> > @viamarit could you please test it with 2022.03 version?
> 
> I upgraded to 2022.03. Still does tot work. The error logged is: 2022-03-02 22:06:35 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.clientraw_temperature (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author. for each Entity

**Comment by viamarit** [comment]
@pilotak 
Hello Pavel, I manually upgrade the eb2e6fb (not through HACS) and now works well. Thanks a lot!

**Comment by vk2him** [comment]
Working fine for me as well on 2022.03.0 - thanks!

**Comment by roosenbrug** [comment]
For me it also did the trick. Works fine now with version 2022.03.0

**Comment by pilotak** [comment]
perfect, i will release it
